### ISSUE TITLE
Rename to goofy

### ISSUE THREAD

**Issue by tamalsaha** [adamryman/go-fuck-yourself#2]
Like `foobar`, renaming it to `goofy` will make it easier to use. :)

**Comment by adamryman** [comment]
Hi! Is it to show people who would not like the current name? Does pull #3 do what you need? You can install it via

```
go get github.com/adamryman/go-fuck-yourself/goofy
```

And it prints something nicer when it is evoked via `goofy` then the normal command.

I could also create another repo for this one, I kind of like the current name personally. Though I am willing to compromise.

**Comment by tamalsaha** [comment]
Sounds good!

**Comment by adamryman** [comment]
@TamalSaha, would you mind giving that pull request a quick review? https://github.com/adamryman/go-fuck-yourself/pull/3/files

Give it an approve if you think it LGTY. And I will merge it.

**Comment by adamryman** [comment]
\ʕ◔ϖ◔ʔ/
